### PR TITLE
Add a fix to StreetTransitLink to allow transfers between stops.

### LINKED ISSUE #10: NJ Transit routing issues
Trains running on the Main Line, Bergen County Line, and Pascack Valley Line of NJ Transit Rail network terminate at Hoboken. Passengers wishing to travel to New York Penn Station must discharge at Lautenberg Secaucus Junction the Lower Level and transfer to a train to New York Penn Station at Secaucus Junction on the Upper Level. The official NJ Transit Rail GTFS lists them as two separate stops though they are the same station. Network map is on bottom page.
Example trip from New York to destinations on Main Line, Bergen County Line, and Pascack Valley Line Main Line, Bergen County Line, and Pascack Valley Line that require transfer at Secacus is correctly shown in Google Maps. Additionally, it is shown correctly on the NJ Transit Trip Planner.
image
[Google Maps](https://www.google.com/maps/dir/New+York+Penn+Station,+New+York,+NY/Teterboro,+NJ/@40.7985717,-74.1120615,12z/data=!3m1!4b1!4m16!4m15!1m5!1m1!1s0x89c259ae15b2adcb:0x7955420634fd7eba!2m2!1d-73.993519!2d40.750568!1m5!1m1!1s0x89c2f9b0a40235f7:0xd81a483d6e7a2235!2m2!1d-74.0593075!2d40.8598219!2m1!5e2!3e3)
511NY does not display the example trip correctly. It appears to be unable to distinguish between the upper levels and lower levers at Secaucus Junction. The result of using 511NY to plan a train only trip from New York to destinations north of Secaucus requires alternative routes that do not involve a transfer at Secaucus Junction. 511NY will route passengers onto the nearby PATH rapid transit line down into Hoboken to transfer to a train going north, which is incorrect. While 511NY will offer many alternatives by bus, it is not displaying the quickest itinerary for a trip by train only.
 
image
[511NY](https://otp.511ny.org/#plan?fromPlace=40.749720000000025%2C-73.99345999999997&toPlace=40.86155000000008%2C-74.05802999999997&date=08%2F19%2F2019&time=4%3A31%20PM&arriveBy=false&wheelchair=false&optimize=QUICK&mode=SUBWAY%2CTRAM%2CRAIL%2CWALK&numItineraries=3)
When testing the NJ Transit Rail GTFS in the Data Manager testing environment, where it is only aware available trips in the NJ Transit Rail GTFS feed without alternative options, it routes passengers past Secaucus Junction on the upper level west to Newark, onto a train east towards Hoboken, and onto a third train passing through Secaucus Junction on the lower level before going to destinations north.
image

[Testing Environment Incorrect Results](https://otp-test.511ny.org/#plan?fromPlace=40.749720000000025%2C-73.99345999999997&toPlace=40.86155000000008%2C-74.05802999999997&date=08%2F19%2F2019&time=4%3A34%20PM&routerId=NJ_TRANSIT_Rail_313bfca7-0436-4bcc-bb25-777b895dfc5f&arriveBy=false&wheelchair=false&optimize=QUICK&mode=TRANSIT%2CWALK&numItineraries=3)
The correct itinerary is shown on the following map where the passenger can transfer between the upper and lower levels at Secaucus Junction.
image
[OTP Trip Planner showing correct map with custom GTFS](https://otp-test.511ny.org/#plan?fromPlace=40.749720000000025%2C-73.99345999999997&toPlace=40.86155000000008%2C-74.05802999999997&date=08%2F19%2F2019&time=4%3A46%20PM&routerId=NJ_Transit_Rail_-_Secaucus_Fix_db31baab-28da-4a4e-8afc-f79b18945b59&arriveBy=false&wheelchair=false&optimize=QUICK&mode=TRANSIT%2CWALK&numItineraries=3)
The NJ Transit Rail GTFS does not have a transfers.txt file to indicate the passenger transfer between the upper and lower level. Adding a custom transfers.txt file that does not specify a minimum transfer time will solve the transfer location issue but creates a new issue where 511NY will not plan trips with enough time to transfer. Adding the correct transfers.txt file that specifies a minimum transfer time theoretically would solve both the transfer location issue and the transfer time issue, but it does not solve either of those issues and instead plans trips with incorrect transfer locations as previously shown.
The official NJ Transit GTFS feed remains in production as it is until a fix is made and is listed in Data Manager as NJ Transit Rail. A feed source for testing fixes is called NJ Transit Rail – Secaucus Fix and can be found under feed sources in Data Manager for testing.

### PR DESCRIPTION
**Pull request by evansiroky**
This PR Fixes #10 by allowing the traversal of two StreetTransit links after another as long as the StreetTransitLinks are for different stops respectively. This allows the creation of SimpleTransfers during the graph build phase and also the proper output of SimpleTransfers in results.

### CODE REVIEW

File: src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java [hunk 1]
```diff
@@ -70,8 +70,13 @@ public String getName(Locale locale) {
...
 
-        // Forbid taking shortcuts composed of two street-transit links in a row. Also avoids spurious leg transitions.
-        if (s0.backEdge instanceof StreetTransitLink) {
+        // Forbid taking shortcuts composed of two street-transit links associated with the same stop in a row. Also
+        // avoids spurious leg transitions. As noted in https://github.com/opentripplanner/OpenTripPlanner/issues/2815,
+        // it is possible that two stops can have the same GPS coordinate thus creating a possibility for a
+        // legitimate StreetTransitLink > StreetTransitLink sequence, so allow two StreetTransitLinks to be taken if
+        // they are for different stops.
+        if (s0.backEdge instanceof StreetTransitLink &&
+            ((StreetTransitLink) s0.backEdge).transitStop == this.transitStop) {
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java:79]: Looks good, thanks for finding this issue. My only comment is that I prefer comments about conditionals to reflect the logic shown in the condition if possible (the last bit of the comment describes the reverse). So, instead of:
```
... so allow two StreetTransitLinks to be taken if they are for different stops.
```
I would prefer:
```
... so only forbid two StreetTransitLinks to be taken if they are for the same stop.
```

**Review by landonreed — APPROVED** [review]
Looks great! Just a nitpick on the code comment.
