### PR TITLE
Handle GBFS Containing Fields Not Used

### LINKED ISSUE #60: OTP fails to load certain GBFS feeds with extra fields
## Expected behavior

OTP should parse the following GBFS feeds without throwing an exception:
- https://gbfs.bcycle.com/bcycle_houston/gbfs.json
- https://gbfs.bcycle.com/bcycle_indego/gbfs.json

## Observed behavior

The feeds above contain extra fields `version`, `last_updated` that are not recognized by the JSON parser,
resulting in the following exception:

`Unrecognized field "version" (class org.opentripplanner.updater.vehicle_rental.GBFSMappings.GbfsResponse), not marked as ignorable`

Occurs on line: https://github.com/ibi-group/OpenTripPlanner/blob/3b44958c4ae60f67d4126c3a3b4678f90fa904a3/src/main/java/org/opentripplanner/updater/bike_rental/GbfsBikeRentalDataSource.java#L124

Example stack trace when polling the `/otp/routers/default/bike_rental` endpoint:
```log
17:19:49.514 ERROR (GbfsBikeRentalDataSource.java:94) [severity: FEED_WIDE] failed to deserialize gbfs.json response (network: GBFS)
17:19:49.522 ERROR (GenericJsonBikeRentalDataSource.java:97) [severity: ALL_STATIONS] Error reading bike rental feed from null (url: null)
java.net.MalformedURLException: null
	at java.net.URL.<init>(URL.java:644) ~[na:1.8.0_261]
	at java.net.URL.<init>(URL.java:507) ~[na:1.8.0_261]
	at java.net.URL.<init>(URL.java:456) ~[na:1.8.0_261]
	at org.opentripplanner.updater.bike_rental.GenericJsonBikeRentalDataSource.update(GenericJsonBikeRentalDataSource.java:106) ~[classes/:na]
	at org.opentripplanner.updater.bike_rental.GbfsBikeRentalDataSource.update(GbfsBikeRentalDataSource.java:67) [classes/:na]
	at org.opentripplanner.updater.bike_rental.BikeRentalUpdater.runPolling(BikeRentalUpdater.java:140) [classes/:na]
	at org.opentripplanner.updater.PollingGraphUpdater.run(PollingGraphUpdater.java:47) [classes/:na]
	at org.opentripplanner.updater.GraphUpdaterManager.lambda$startUpdaters$1(GraphUpdaterManager.java:162) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]
Caused by: java.lang.NullPointerException: null
	at java.net.URL.<init>(URL.java:549) ~[na:1.8.0_261]
	... 10 common frames omitted
17:19:49.523 ERROR (GenericJsonBikeRentalDataSource.java:97) [severity: ALL_FLOATING_VEHICLES] Error reading bike rental feed from null (url: null)
java.net.MalformedURLException: null
	at java.net.URL.<init>(URL.java:644) ~[na:1.8.0_261]
	at java.net.URL.<init>(URL.java:507) ~[na:1.8.0_261]
	at java.net.URL.<init>(URL.java:456) ~[na:1.8.0_261]
	at org.opentripplanner.updater.bike_rental.GenericJsonBikeRentalDataSource.update(GenericJsonBikeRentalDataSource.java:106) ~[classes/:na]
	at org.opentripplanner.updater.bike_rental.GbfsBikeRentalDataSource.update(GbfsBikeRentalDataSource.java:69) [classes/:na]
	at org.opentripplanner.updater.bike_rental.BikeRentalUpdater.runPolling(BikeRentalUpdater.java:140) [classes/:na]
	at org.opentripplanner.updater.PollingGraphUpdater.run(PollingGraphUpdater.java:47) [classes/:na]
	at org.opentripplanner.updater.GraphUpdaterManager.lambda$startUpdaters$1(GraphUpdaterManager.java:162) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]
Caused by: java.lang.NullPointerException: null
	at java.net.URL.<init>(URL.java:549) ~[na:1.8.0_261]
	... 10 common frames omitted
17:19:49.523 ERROR (GbfsBikeRentalDataSource.java:94) [severity: FEED_WIDE] Both station and vehicle info not found! (network: GBFS)

```

## Version of OTP used (exact commit hash or JAR name)

https://github.com/ibi-group/OpenTripPlanner/commit/95788c8c4b0c18065885ca7bd9af7e6c729e1bbf

## Data sets in use (links to GTFS and OSM PBF files)

- https://gbfs.bcycle.com/bcycle_houston/gbfs.json
- https://gbfs.bcycle.com/bcycle_indego/gbfs.json

## Command line used to start OTP

`--autoScan --server --port 8080 --basePath <path-to-otp-data>`

## Router config and graph build config JSON

```json
{
  // ... other configs...

  "updaters": [
    {
      "type": "bike-rental",
      "sourceType": "gbfs",
      "url": "https://gbfs.bcycle.com/bcycle_houston",
      "frequencySec": 30
    }

    // other updaters
  ]
}
```

## Steps to reproduce the problem

Query the `bike_rental` endpoint. An error message is returned and the exception appears in the terminal/logs.

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
Closes #60. The issue was not only the JSON types being too strongly enforced, but the opposite as well! There was no code to handle an expected feed not being present. A small check has been added.

To be completed by pull request submitter:

- [X] **issue**: Link to or create an [issue](https://github.com/opentripplanner/OpenTripPlanner/issues) that describes the relevant feature or bug. Add [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/) to this PR's description (e.g., `closes #45`).
- [x] **roadmap**: Check the [roadmap](https://github.com/orgs/opentripplanner/projects/1) for this feature or bug. If it is not already on the roadmap, PLC will discuss as part of the review process.
- [ ] **tests**: Have you added relevant test coverage? Are all the tests passing on [the continuous integration service (Travis CI)](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#continuous-integration)?
- [x] **formatting**: Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#code-style)? 
- [x] **documentation**: If you are adding a new configuration option, have you added an explanation to the [configuration documentation](docs/Configuration.md) tables and sections?
- [ ] **changelog**: add a bullet point to the [changelog file](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Changelog.md) with description and link to the linked issue

To be completed by @opentripplanner/plc:

- [ ] reviews and approvals by 2 members, ideally from different organizations
- [ ] **after merging**: update the relevant card on the [roadmap](https://github.com/orgs/opentripplanner/projects/1)

### CODE REVIEW

File: src/main/java/org/opentripplanner/updater/bike_rental/GbfsBikeRentalDataSource.java [hunk 1]
```diff
@@ -22,6 +23,7 @@
 /**
  * Created by demory on 2017-03-14.
  */
+@JsonIgnoreProperties(ignoreUnknown = true)
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/updater/bike_rental/GbfsBikeRentalDataSource.java]: At first glance, I don't think this class or `GenericJsonBikeRentalDataSource.java` should need these annotations. The `@JsonIgnoreProperties` annotation is only meant for classes that are serialized/deserialized like the `GbfsResponse.java`. Did you try to resolve things without adding the annotation to these first two classes in the list of files?

File: src/main/java/org/opentripplanner/updater/bike_rental/GenericJsonBikeRentalDataSource.java [hunk 2]
```diff
@@ -98,11 +100,15 @@ private void addError(String message, Exception e) {
...
     @Override
+    @JsonIgnoreProperties(ignoreUnknown = true)
     public boolean update() {
         errors = new LinkedList<>();
 
         InputStream data = null;
         try {
+            if(url == null){
+                return false;
+            }
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/updater/bike_rental/GenericJsonBikeRentalDataSource.java]: Slight syntax tweak (spaces). Does this comment reflect the intention? If not, feel free to provide a better one.
```suggestion
            if (url == null) {
                // If the file is not expected to exist, return false without an error.
                return false;
            }
```

File: src/main/java/org/opentripplanner/updater/bike_rental/GbfsBikeRentalDataSource.java (hunk 1 above)
Comment (miles-grant-ibigroup) [reply src/main/java/org/opentripplanner/updater/bike_rental/GbfsBikeRentalDataSource.java]: That's my Jackson inexperience! Thanks for clearing it up. Works perfectly when removing the unneeded annotations!

File: src/main/java/org/opentripplanner/updater/bike_rental/GenericJsonBikeRentalDataSource.java (hunk 2 above)
Comment (miles-grant-ibigroup) [reply src/main/java/org/opentripplanner/updater/bike_rental/GenericJsonBikeRentalDataSource.java]: That's exactly it thanks so much!

File: src/main/java/org/opentripplanner/updater/vehicle_rental/GBFSMappings/GbfsResponse.java [hunk 3]
```diff
@@ -9,6 +11,7 @@
  * Response class for the gbfs.json file.
  * See https://github.com/NABSA/gbfs/blob/master/gbfs.md#gbfsjson
  */
+@JsonIgnoreProperties(ignoreUnknown = true)
```
Comment (evansiroky) [inline src/main/java/org/opentripplanner/updater/vehicle_rental/GBFSMappings/GbfsResponse.java]: Could this be applied instead to the `BaseGtfsResponse` and have a cascading effect to other mappings that extend this class?

**Review by evansiroky — APPROVED** [review]
If implementing the change in my comment works, then I approve with those changes.

**Comment by miles-grant-ibigroup** [comment]
Not only does it work to move the annotation up the class hierarchy, it's a really good idea!

All its children may have extra data

**Review by landonreed — APPROVED** [review]
Looks good. I hate to add one more thing to the list, but it looks like that class' name might need to be refactored from `BaseGtfsResponse` to `BaseGbfsResponse`.

**Comment by evansiroky** [comment]
> Looks good. I hate to add one more thing to the list, but it looks like that class' name might need to be refactored from `BaseGtfsResponse` to `BaseGbfsResponse`.

oops, not sure how I managed to do that originally

**Comment by miles-grant-ibigroup** [comment]
Well spotted! Have refactored the class
